# Site settings
title: Andy Kelleher Stuhl
email: akstuhl@mit.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm a graduate student in [Comparative Media Studies at MIT](http://cmsw.mit.edu/) 
  and a research assistant in [HyperStudio](http://hyperstudio.mit.edu/).
  My work centers on creative infrastructures and the politics
  of sound technologies, which I explore from various angles within
  sound studies, interaction design, and the digital humanities.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://akstuhl.github.io" # the base hostname & protocol for your site
twitter_username: akstuhl
github_username:  akstuhl
permalink: none

collections:
  mixed_messages:
    output: true
    
defaults:
  -
    scope:
      path: ""
      type: "mixed_messages"
    values:
      excerpt: Mixed Messages is a 40-day correspondence between Leigh Kaulbach and Andy Kelleher Stuhl through sound and image.
      layout: "mm_post"

# Build settings
markdown: kramdown
