# Site settings
title: Andy Kelleher Stuhl
email: andykstuhl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a media researcher, software developer, and audio experimenter. Right now I'm a PhD candidate in Communication Studies at McGill, where my dissertation traces the cultural meaning of automation in radio and sound art.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://akstuhl.github.io" # the base hostname & protocol for your site
twitter_username: akstuhl
github_username:  akstuhl
soundcloud_username: andykstuhl
permalink: none

plugins:
  - jekyll-target-blank

collections:
  mixed_messages:
    output: true
  blog:
    output: true
  pie:
    output: true
  index_items:
    output: false
  tuning:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "mixed_messages"
    values:
      excerpt: Mixed Messages is a 40-day correspondence between Leigh Kaulbach and Andy Kelleher Stuhl through sound and image.
      layout: "mm_post"

stuff_lists:
  -
    slug: stuff-done
    heading: "Stuff I've done"
  -
    slug: stuff-doing
    heading: "Stuff I'm doing"
  -
    slug: stuff-using
    heading: "Stuff I use"

# Build settings
markdown: kramdown
