# Site settings
title: Andy Kelleher Stuhl
email: andykstuhl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a writer, sound artist, and software developer focused on
  creative infrastructures and the politics of sonic encounters
  with technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://akstuhl.github.io" # the base hostname & protocol for your site
twitter_username: akstuhl
github_username:  akstuhl
soundcloud_username: andykstuhl
permalink: none

collections:
  mixed_messages:
    output: true
  blog:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "mixed_messages"
    values:
      excerpt: Mixed Messages is a 40-day correspondence between Leigh Kaulbach and Andy Kelleher Stuhl through sound and image.
      layout: "mm_post"

# Build settings
markdown: kramdown
