# Site settings
title: Andy Kelleher Stuhl
email: andykstuhl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I research sonic arts, computation, and media change. My dissertation, for Communication Studies at McGill, traces automation's industrial development and cultural contestation across sixty years of radio history.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://akstuhl.github.io" # the base hostname & protocol for your site
github_username:  akstuhl
soundcloud_username: andykstuhl
permalink: none
timezone: America/New_York

plugins:
  - jekyll-target-blank

collections:
  mixed_messages:
    output: true
  blog:
    output: true
  pie:
    output: true
  radio_automation:
    output: true
  stuff:
    output: true
  tuning:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "mixed_messages"
    values:
      excerpt: Mixed Messages is a 40-day correspondence between Leigh Kaulbach and Andy Kelleher Stuhl through sound and image.
      layout: "mm_post"
  -
    scope:
      path: ""
      type: "stuff"
    values:
      layout: "stuff-item"

stuff_lists:
  -
    slug: stuff-done
    heading: "Stuff I've done"
  -
    slug: stuff-doing
    heading: "Stuff I'm doing"
  -
    slug: stuff-using
    heading: "Stuff I use"

# Build settings
markdown: kramdown
